# Generated by Django 4.2.2 on 2023-06-17 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='translation',
            field=models.CharField(default='no translation', max_length=100),
        ),
        migrations.AlterField(
            model_name='grammar',
            name='word',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grammar_rules', to='dictionary.word'),
        ),
    ]
