# Generated by Django 4.2.2 on 2023-06-17 20:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0003_alter_word_translation'),
    ]

    operations = [
        migrations.CreateModel(
            name='WordFTS',
            fields=[
                ('word', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='dictionary.word')),
                ('content', models.TextField()),
            ],
        ),
    ]
